# ------------------------------------------------------------------------------
# Project : CNLib                                                  /          \
# Filename: mkdocs.yml                                            |     ()     |
# Date    : 01/01/2026                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

site_name: CNLib
theme: readthedocs
docs_dir: docs
site_dir: site
plugins:
    - search
    - mkdocstrings

# -)
