# ------------------------------------------------------------------------------
# Project : CNLib                                                  /          \
# Filename: mkdocs.yml                                            |     ()     |
# Date    : 09/15/2025                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

site_name: CNLib
theme: 
docs_dir: docs
site_dir: site
plugins:
  - search
  - mkdocstrings

# -)
